# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
   - r: release
     after_success:
       - Rscript -e 'covr::codecov()'
   - r: devel
     r_build_args: --no-build-vignettes
     r_check_args: --ignore-vignettes --no-examples
   - r: oldrel
     r_build_args: --no-build-vignettes
     r_check_args: --ignore-vignettes --no-examples
